name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pr:
    name: PR Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: PR Checks
        run: bun run pr:check

      - name: Upload results to Codecov
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: felix-dolderer/felix-dolderer-com
